apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualsubnetcalc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualsubnetcalc
  template:
    metadata:
      labels:
        app: visualsubnetcalc
    spec:
      containers:
        - name: visualsubnetcalc
          image: ghcr.io/lzhengqc/visualsubnetcalc:pr-7
          ports:
            - containerPort: 8080
